#pragma once
//
// MotorController — owns the six stepper STEP/DIR/EN lines and the EN safe state.
//
// Responsibilities (spec §4, §8):
//   * Take a per-channel step rate in Hz and ramp toward it (soft accel/decel) —
//     never an instantaneous jump.
//   * Own the EN lines and the safe-shutdown path. EN is active-LOW and defaults
//     DISABLED at boot (external pull-up); drivers are only enabled once ready.
//
// STEP pulses are generated by MCPWM, not RMT/FastAccelStepper: the ESP32-S3 has
// only 4 RMT channels (and LEDC has only 4 usable timers), but MCPWM has 2 units x
// 3 timers = 6 independent timers — exactly one per arc, each free to run its own
// speed. Mapping: channel i -> MCPWM unit i/3, timer i%3, generator A. A 50%-duty
// square wave on that output is the step train; its frequency is the speed.
//
// TMC2209s run in STEP/DIR mode; phase current is set in hardware by each driver's
// potentiometer, not here.
//

#include <stdint.h>
#include "config.h"

// A step rate the hardware will actually emit: 0 (stopped), else MIN..MAX Hz.
// Shared with the web UI so a typed rate is clamped the same way everywhere.
inline uint16_t motorClampHz(long hz) {
  if (hz <= 0) return 0;
  if (hz < (long)MOTOR_MIN_SPEED_HZ) return (uint16_t)MOTOR_MIN_SPEED_HZ;
  if (hz > (long)MOTOR_MAX_SPEED_HZ) return (uint16_t)MOTOR_MAX_SPEED_HZ;
  return (uint16_t)hz;
}

class MotorController {
 public:
  // Configure every channel's MCPWM timer + pins and enable the drivers that came
  // up. Returns false (-> Fault::Motor) if ANY channel failed to initialise — but
  // the channels that did initialise are still enabled and usable.
  bool begin();

  // Set the target step rate for one channel, in Hz. 0 stops (ramped); anything
  // else is clamped into MIN..MAX.
  void setTarget(uint8_t ch, uint16_t hz);
  void setTargets(const uint16_t values[NUM_CHANNELS]);

  // Pump the soft-start ramp and push new frequencies to MCPWM. Call every loop.
  void update();

  // Safe shutdown: stop all pulses and drive every EN to the disabled state.
  // Called on fault and before a deliberate reset.
  void emergencyStop();

  uint32_t targetHz(uint8_t ch) const { return ch < NUM_CHANNELS ? targetHz_[ch] : 0; }
  uint32_t commandedHz(uint8_t ch) const { return ch < NUM_CHANNELS ? commandedHz_[ch] : 0; }
  bool     channelOk(uint8_t ch) const { return ch < NUM_CHANNELS && channelOk_[ch]; }
  bool     ok() const { return ok_; }
  bool     enabled() const { return enabled_; }

 private:
  void     emitChannel(uint8_t ch, uint32_t hz);   // drive a 50% square wave at hz
  void     stopChannel(uint8_t ch);                // hold STEP low, no pulses

  uint32_t targetHz_[NUM_CHANNELS]    = {0};       // 0, or MIN..MAX Hz
  float    currentHz_[NUM_CHANNELS]   = {0};       // ramped actual; 0 == stopped
  uint32_t commandedHz_[NUM_CHANNELS] = {0};       // freq last written to MCPWM
  bool     channelOk_[NUM_CHANNELS]   = {false};   // this channel's MCPWM came up
  uint32_t lastUpdateMs_ = 0;
  bool     ok_ = false;                            // all channels initialised
  bool     enabled_ = false;                       // at least one channel running
};
